---
name: CI

on:
  push:

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "example"

name: Lint

on:
  push:
  workflow_dispatch:

jobs:
  build:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@dojo

      - name: Lint
        uses: docker://github/super-linter:v3